### ISSUE TITLE
Image Viewer?

### ISSUE THREAD

**Issue by ckuethe** [f-secure-foundry/interlock#44]
If it's not too much trouble, could you add an image viewer and/or some kind of raw mode, so that I can keep images and pdfs in encrypted storage and view the contents in my browser without downloading to the host?

**Comment by abarisani** [comment]
For PDFs I think setting the Content Type accordingly would allow the browser to open them directly (which would be practically equivalent, but much easier, than having a renderer in INTERLOCK itself).

For images maybe @danbia can comment on how feasible it would be ?
