### ISSUE TITLE
How to decrypt a file?

### ISSUE THREAD

**Issue by vonProteus** [f-secure-foundry/interlock#47]
i encrypt file with aes-256-ofb and passphrase via webui
when i try to decrypt it via
```
usbarmory@usbarmory:~/.interlock-mnt$ openssl enc -d -aes-256-ofb -in file.txt.aes256ofb -out file.txt.aes256ofb.txt
bufsize=8192
enter aes-256-ofb decryption password:
bad magic number
``` 
i tried on my local machine and result is the same
decryption in webui works

interlock.conf
```
{
  "debug": true,
  "static_path": "static",
  "set_time": false,
  "bind_address": "0.0.0.0:4430",
  "tls": "gen",
  "tls_cert": "certs/cert.pem",
  "tls_key": "certs/key.pem",
  "tls_client_ca": "",
  "hsm": "off",
  "key_path": "keys",
  "volume_group": "usbarmory-sd",
  "ciphers": [
          "OpenPGP",
          "AES-256-OFB",
          "TOTP"
  ]
}
```

**Comment by abarisani** [comment]
The encryption performed in INTERLOCK is not meant to be compatible with openssl as it has a specific format, see [here](https://github.com/f-secure-foundry/interlock/blob/master/internal/aes.go#L22).

**Comment by vonProteus** [comment]
ok is not compatible with openssl
so what is the rationale behind this feature?
if i need INTERLOCK to decrypt file

i thought it was used like this:
* i connect INTERLOCK to insecure computer
* i connect to it
* i decrypt luks volume (in borrower)
* i encrypt file with AES-256-OFB and password
* i download encrypted file
* and i can send encrypted file to someone eg vie email
* then recipient decrypt file in some way eg openssl

**Comment by abarisani** [comment]
The rationale is to decrypt it in INTERLOCK itself, again we are not claiming openssl compatibility. If you require compatibility you can encrypt/decrypt with INTERLOCK OpenPGP support.
